#!/usr/bin/env python3

import sys
import argparse
import json
import concurrent.futures
from utils import *
from aruba_query import *
from constants import *

requests.packages.urllib3.disable_warnings()


def main():
    # CLI parser for the command
    parser = argparse.ArgumentParser(description="Reboot Aruba AP")

    # Get input from CLI
    parser.add_argument(
        "--mac",
        help="Enter the MAC Address of the AP to reboot",
    )
    parser.add_argument(
        "--name",
        help="Enter the AP name to reboot",
    )
    parser.add_argument(
        "--blink-on",
        action="store_true",
        default=False,
        help="Turn on LED Blinking",
    )
    parser.add_argument(
        "--blink-off",
        action="store_true",
        default=False,
        help="Turn off LED Blinking",
    )

    # parse the arguments and print help if there are none
    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    # read CLI into args
    args = parser.parse_args()

    query = ArubaQuery()
    inventory = ArubaInventory()
    arubapost = ArubaPost()

    # get the api token for all controllers
    with concurrent.futures.ThreadPoolExecutor() as executor:
        for wc in MOBILITY_CONTROLLERS:
            executor.submit(query.get_aruba_api_token, wc, PASSWORD, inventory)

    with concurrent.futures.ThreadPoolExecutor() as executor:
        for wc in MOBILITY_CONTROLLERS:
            executor.submit(arubapost.blink_ap, wc, inventory, args, query)


if __name__ == "__main__":
    main()
