#!/usr/bin/env python3


CONFIG_PATH = "/md"
USERNAME = ""
PASSWORD = ""
MOBILITY_CONDUCTORS = []
MOBILITY_CONTROLLERS = []
# gsheet API settings
SERVICE_ACCOUNT_EMAIL = ""
PROJECT_ID = ""
CLIENT_ID = ""
PRIVATE_KEY_ID = ""
PRIVATE_KEY = ""
#Slack Credentials
SLACK_BOT_TOKEN = ""
SLACK_APP_TOKEN = ""
